server.port=8080
spring.application.name=greenbite-bff

# URLs de los microservicios (en K8s serían nombres de servicio)
greenbite.ms.suscripciones.url=http://ms-suscripciones:8081
greenbite.ms.catalogo.url=http://ms-catalogo:8082

# CORS
greenbite.cors.allowed-origins=http://localhost:3000

# Actuator (health check para Kubernetes)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
